# Code generated by protoc-gen-rbi. DO NOT EDIT.
# source: example.proto
# typed: strict

module Example::Greeter
  class Service
    include ::GRPC::GenericService
  end

  class Stub < ::GRPC::ClientStub
    sig do
      params(
        host: String,
        creds: T.any(::GRPC::Core::ChannelCredentials, Symbol),
        kw: T.untyped,
      ).void
    end
    def initialize(host, creds, **kw)
    end

    sig do
      params(
        request: Example::Request
      ).returns(Example::Response)
    end
    def hello(request)
    end
  end

  sig do
    params(
      name: T.nilable(String),
      count: T.nilable(Integer),
      test_list: T.nilable(T.any(T::Array[String], ::Google::Protobuf::RepeatedField[String]))
    ).returns(Example::Response)
  end
  def self.hello(
    name: "",
    count: 0,
    test_list: []
  )
  end
end
