# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("example.proto", :syntax => :proto3) do
    add_message "example.Request" do
      optional :name, :string, 1
      proto3_optional :count, :int32, 2
      repeated :test_list, :string, 3
      optional :example, :message, 4, "example.Request.Example"
      proto3_optional :optional_example, :message, 5, "example.Request.Example"
    end
    add_message "example.Request.Example" do
      optional :field, :string, 1
    end
    add_message "example.Response" do
      optional :greeting, :string, 1
    end
    add_enum "example.ExampleState" do
      value :EXAMPLE_STATE_UNSPECIFIED, 0
      value :EXAMPLE_STATE_PENDING, 1
      value :EXAMPLE_STATE_ACTIVE, 2
    end
  end
end

module Example
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Request").msgclass
  Request::Example = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Request.Example").msgclass
  Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.Response").msgclass
  ExampleState = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.ExampleState").enummodule
end
